$background = 130d09
$onBackground = f8e1d6
$surface = 130d09
$surfaceDim = 130d09
$surfaceBright = 372922
$surfaceContainerLowest = 000000
$surfaceContainerLow = 1a120d
$surfaceContainer = 211712
$surfaceContainerHigh = 281d17
$surfaceContainerHighest = 30231c
$onSurface = f8e1d6
$surfaceVariant = 30231c
$onSurfaceVariant = bca79d
$outline = 847269
$outlineVariant = 54453d
$inverseSurface = fff8f6
$inverseOnSurface = 5d534e
$shadow = 000000
$scrim = 000000
$surfaceTint = f6b998
$primary = f6b998
$primaryDim = e7ac8b
$onPrimary = 5f361d
$primaryContainer = 74482e
$onPrimaryContainer = ffdccb
$inversePrimary = 835439
$primaryFixed = f3b695
$primaryFixedDim = e4a989
$onPrimaryFixed = 442009
$onPrimaryFixedVariant = 673d24
$secondary = e6beaa
$secondaryDim = d7b19d
$onSecondary = 553a2b
$secondaryContainer = 4f3527
$onSecondaryContainer = deb7a3
$secondaryFixed = ffdbc9
$secondaryFixedDim = f4ccb8
$onSecondaryFixed = 54392b
$onSecondaryFixedVariant = 735545
$tertiary = fff6e1
$tertiaryDim = f6e29c
$onTertiary = 6b5d25
$tertiaryContainer = fce7a1
$onTertiaryContainer = 62541d
$tertiaryFixed = fce7a1
$tertiaryFixedDim = eed995
$onTertiaryFixed = 4f420c
$onTertiaryFixedVariant = 6d5e26
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 9e6b4f
$secondaryPaletteKeyColor = 91705f
$tertiaryPaletteKeyColor = 86763c
$neutralPaletteKeyColor = 807570
$neutralVariantPaletteKeyColor = 85736a
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 9e6b4f
$secondary_paletteKeyColor = 91705f
$tertiary_paletteKeyColor = 86763c
$neutral_paletteKeyColor = 807570
$neutral_variant_paletteKeyColor = 85736a
$term0 = 353433
$term1 = f46300
$term2 = ffbf88
$term3 = ffe0cd
$term4 = b9ab66
$term5 = f19272
$term6 = febc73
$term7 = eed3c3
$term8 = b39f93
$term9 = ff884c
$term10 = ffd5b5
$term11 = fff1ea
$term12 = dcbc93
$term13 = ffaa8c
$term14 = ffd3a9
$term15 = ffffff
$rosewater = ffeee8
$flamingo = ffdacc
$pink = ffd3c8
$mauve = ffab9d
$red = ff9a74
$maroon = f9ac8f
$peach = ffc09e
$yellow = ffeee4
$green = ffd9b4
$teal = ffdb94
$sky = e1df87
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbcbb
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = ce5f47
$kvisitedSelection = ce5f47
$knegative = e65c0b
$knegativeSelection = e65c0a
$kneutral = ff8c43
$kneutralSelection = ff8c42
$kpositive = ed9600
$kpositiveSelection = ed9600
$text = f8e1d6
$subtext1 = bca79d
$subtext0 = 847269
$overlay2 = 74645b
$overlay1 = 63544d
$overlay0 = 534740
$surface2 = 443933
$surface1 = 342b26
$surface0 = 241c17
$base = 130d09
$mantle = 130d09
$crust = 120c09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
