require('plugins')
require('options')

-- Initialize plugins
require("oil").setup()
require("telescope").setup()
require("typst-preview").setup()

-- User config
require('config/themes/catppuccin')
require('config/themes/gruvbox')
require('config/themes/gruvbox-baby')
require('config/treesitter')
require('config/lsp')
require('config/lualine')
require('config/presence')
require('config/autopairs')
require('config/autotag')
-- require('config/neorg')
require('config/harpoon')
require('config/neoscroll')
require('config/gitsigns')
require('config/dashboard')
require('config/ibl')
require('config/vimtex')
require('config/themery')
